AI_SOFTWARE_KEYWORDS = [
    "midjourney",
    "dall-e",
    "dalle",
    "openai",
    "chatgpt",
    "stable diffusion",
    "stability ai",
    "comfyui",
    "automatic1111",
    "a1111",
    "firefly",
    "adobe firefly",
    "runway",
    "sora",
    "leonardo",
    "ideogram",
    "flux",
    "krea",
    "recraft",
    "playground",
    "dreamstudio",
    "novelai",
]

